---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 123.
--- DateTime: 2023/3/30 4:01
---
---@class ObjectPoolContainer
ObjectPoolContainer = {}

function ObjectPoolContainer:new()
    local o = {};
    setmetatable(o, self);
    self.__index = self;
    --对象
    self.Item = nil
    --是否处于使用状态
    self.Used = false
    return o
end

function ObjectPoolContainer:SetItem(Item)
    self.Item = Item
end

function ObjectPoolContainer:GetItem(Item)
    return self.Item
end

---转为未使用状态
function ObjectPoolContainer:Consume()
    self.Used = true
end

---设置为使用状态
function ObjectPoolContainer:Release()
    self.Used = false
end